[package]
name = "icicle-pingu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icicle-vm = { path = "../icicle-emu/icicle-vm" }
icicle-mem = { path = "../icicle-emu/icicle-mem" }
